databases:
  flight_db:
    user: postgres
    password: password
    db: flight_db
    host: flight_database
    port: 5432
  ticket_db:
    user: postgres
    password: password
    db: ticket_db
    host: ticket_database
    port: 5432
services:
  flight:
    host: "0.0.0.0"
    port: 8060
    log_level: "info"
    reload: True
  ticket:
    host: "0.0.0.0"
    port: 8070
    log_level: "info"
    reload: True
