version: '3.1'

services:
  flight_database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flight_db
    volumes:
      - ./db_data_flight:/var/lib/postgresql/data
      - ./flight_service/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  ticket_database:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticket_db
    volumes:
      - ./db_data_ticket:/var/lib/postgresql/data
      - ./ticket_service/sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  flight_service:
    image: flight_service
    build:
      context: "."
      dockerfile: ./flight_service/Dockerfile
    ports:
      - "8060:8060"
    networks:
      - default
    depends_on:
      flight_database:
        condition: service_healthy

  ticket_service:
    image: ticket_service
    build:
      context: "."
      dockerfile: ./ticket_service/Dockerfile
    ports:
      - "8070:8070"
    networks:
      - default
    depends_on:
      ticket_database:
        condition: service_healthy

volumes:
  db_data_flight:
    driver: local
  db_data_ticket:
    driver: local

networks:
  default:
