version: '3.1'

services:
  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flight_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
      # - ./sql/create_db.sql:/docker-entrypoint-initdb.d/01-create_db.sql
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/02-init_db.sql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  
  flight:
    image: flight
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8060:8060"
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy

volumes:
  db_data:
    driver: local

networks:
  default:
